const { Collection } = require('discord.js')
/**
 * Frieldly permissions Collection
 * @type { Collection<string,string> } 
 */
const permissions =  new (require('discord.js')).Collection()
.set('ADMINISTRATOR','Administrator')
.set('CREATE_INSTANT_INVITE','Create Invites')
.set('KICK_MEMBERS','Kick Members')
.set('BAN_MEMBERS','Ban Members')
.set('MANAGE_CHANNELS','Manage Channels')
.set('MANAGE_GUILD','Manage Server')
.set('ADD_REACTIONS','Add Reactions')
.set('VIEW_AUDIT_LOG','View Audit Logs')
.set('PRIORITY_SPEAKER','Priority Speaker')
.set('VIEW_CHANNEL','View Channels')
.set('SEND_MESSAGES','Send Messages')
.set('SEND_TTS_MESSAGES','Send TTS Message')
.set('MANAGE_MESSAGES','Manage Messages')
.set('EMBED_LINKS','Embed Links')
.set('ATTACH_FILES','Attach Files')
.set('READ_MESSAGE_HISTORY','Read Message History')
.set('MENTION_EVERYONE','Mention Everyone')
.set('USE_EXTERNAL_EMOJIS','Use External Emojis')
.set('CONNECT','Connect')
.set('SPEAK','Speak')
.set('MUTE_MEMBERS','Mute Members')
.set('DEAFEN_MEMBERS','Deafen Members')
.set('MOVE_MEMBERS','Move Members')
.set('USE_VAD','Use Voice Activity Detetction')
.set('CHANGE_NICKNAME0','Change Nickname')
.set('MANAGE_NICKNAMES','Manage Nicknames')
.set('MANAGE_ROLES','Manage Roles')
.set('MANAGE_WEBHOOKS','Manage Webhooks')
.set('MANAGE_EMOJIS','Manage Emojis')
//Deprecated
.set("EXTERNAL_EMOJIS","external emojis")
.set("READ_MESSAGES","Read Messages")
.set("MANAGE_ROLES_OR_PERMISSIONS",'Manage Roles or Permissions')
module.exports = permissions